services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Логические директивы.
  Local\Bundles\SymfonyBladeBundle\Services\Directives\BladeIsDirectives:
    class: Local\Bundles\SymfonyBladeBundle\Services\Directives\BladeIsDirectives
    tags:
      - { name: bitrix.custom.directive }
