services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  ############
  # PSR кэшер
  ############
  instagram_parser_rapid_api.cacher:
    public: false
    class: WebArch\BitrixCache\AntiStampedeCacheAdapter
    arguments: ['/', '%instagram_parser_rapid_api.cache_ttl%', '%instagram_parser_rapid_api.cache_path%']

  # Транспорт, обращающийся к rapidAPI.
  instagram_parser_rapid_api.rapid_api:
    public: false
    class: Local\Bundles\InstagramParserRapidApiBundle\Services\RetrieverInstagramDataRapidApi
    arguments:
      - '@instagram_parser_rapid_api.cacher'
      - '%instagram_parser_rapid_api.instagram_user_id%'
      - '%instagram_parser_rapid_api.rapid_api_key%'
      - '%instagram_parser_rapid_api.after_param%'
    calls:
      - setUseMock: ['%instagram_parser_rapid_api.mock%', '%instagram_parser_rapid_api.fixture_path%']

  # Трансформер данных, получаемых из rapidAPI.
  instagram_parser_rapid_api.data_transformer:
    public: false
    class: Local\Bundles\InstagramParserRapidApiBundle\Services\InstagramDataTransformerRapidApi

  Local\Bundles\InstagramParserRapidApiBundle\Services\InstagramDataTransformerRapidApi: '@instagram_parser_rapid_api.data_transformer'

  # Оркестратор парсера.
  instagram_parser_rapid_api.parser:
    public: true
    class: Local\Bundles\InstagramParserRapidApiBundle\Services\ComplexParser
    arguments: ['@instagram_parser_rapid_api.rapid_api', '@instagram_parser_rapid_api.data_transformer']
    calls:
      - setCount: [3]

  Local\Bundles\InstagramParserRapidApiBundle\Services\ComplexParser: '@instagram_parser_rapid_api.parser'