##############
# Контроллеры
##############

services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Local\Services\Twig\Tools\TemplateControllerContainerAware:
    arguments: ['@Local\SymfonyTools\ArgumentsResolvers\Supply\ResolveParamsFromContainer', '@twig.instance']
